name: TimerPluginAtJava
version: ${project.version}
main: test.tonatumi.timerpluginatjava.TimerPluginAtJava
commands:
  timer:
    description: show timer help
    usage: /<command>
    default: true
